### ISSUE TITLE
volterra mcn - gcp destroy fails the first time 

### ISSUE THREAD

**Issue by yossi-r** [f5devcentral/f5-digital-customer-engagement-center#156] opened 2021-08-31 14:33 UTC
when destroying the GCP deployment in the /solutions/volterra/multi-cloud-networking, i get the following error:
Error: Error when reading or editing Subnetwork: googleapi: Error 400: The subnetwork resource 'projects/f5-gcs-4261-sales-na-w/regions/us-west1/subnetworks/yos-mcn-outside-1a25' is already being used by 'projects/f5-gcs-4261-sales-na-w/zones/us-west1-b/instances/yos-mcn-bu21-gcp-1a25-rtvs', resourceInUseByAnotherResource

Error: Error when reading or editing Subnetwork: googleapi: Error 400: The subnetwork resource 'projects/f5-gcs-4261-sales-na-w/regions/us-west1/subnetworks/yos-mcn-bu22-inside-1a25' is already being used by 'projects/f5-gcs-4261-sales-na-w/zones/us-west1-b/instances/yos-mcn-bu22-gcp-1a25-x9xc', resourceInUseByAnotherResource

Error: Error when reading or editing Subnetwork: googleapi: Error 400: The subnetwork resource 'projects/f5-gcs-4261-sales-na-w/regions/us-west1/subnetworks/yos-mcn-bu23-inside-1a25' is already being used by 'projects/f5-gcs-4261-sales-na-w/zones/us-west1-b/instances/yos-mcn-bu23-gcp-1a25-5f69', resourceInUseByAnotherResource

Error: Error when reading or editing Subnetwork: googleapi: Error 400: The subnetwork resource 'projects/f5-gcs-4261-sales-na-w/regions/us-west1/subnetworks/yos-mcn-bu21-inside-1a25' is already being used by 'projects/f5-gcs-4261-sales-na-w/zones/us-west1-b/instances/yos-mcn-bu21-gcp-1a25-rtvs', resourceInUseByAnotherResource

waiting 5 minutes after the error and destroying again solved the issue

**Comment by memes** [comment] 2021-08-31 15:16
This is due to the underlying use of stateful MIG by Volterrra - `volterra_tf_params_action` resource returns success after initiating the destruction of Volterra gateways but before the instances are actually removed. Can't delete a VPC network when there are still VMs attached to it.

Tempted to mark as `wontfix` because the issue is in the provider, but I guess a timeout could be added to the destruction phase although any selected duration will pause the destroy for the fixed number of seconds.

**Closed** 2021-11-06 19:12 UTC
Labels: bug, wontfix
